/**
 * Custom Worker entrypoint (wrangler `main`).
 *
 * Wraps the OpenNext-generated handler so the app Worker can also consume the
 * `monitor-sweeps` queue — likeness sweeps run 5-15 minutes, far past what a
 * request-path waitUntil() survives, and queue delivery redelivers if the
 * isolate dies mid-sweep (see lib/monitor/sweep-queue.ts for the semantics).
 *
 * Everything imported from .open-next/ is generated by `npm run cf:build`;
 * wrangler bundles this file, resolving those imports at deploy/preview time.
 *
 * runWithCloudflareRequestContext() is the same wrapper the generated fetch
 * handler uses: it establishes the AsyncLocalStorage that
 * getCloudflareContext() reads and populates process.env from bindings. With
 * the queue handler wrapped in it, the whole lib/ graph (getDb, sendEmail,
 * callAi, notifications) works exactly as it does on a request.
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment -- resolves only after `npm run cf:build`, so ts-expect-error would flip post-build
// @ts-ignore
import handler from "./.open-next/worker.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment -- resolves only after `npm run cf:build`, so ts-expect-error would flip post-build
// @ts-ignore
import { runWithCloudflareRequestContext } from "./.open-next/cloudflare/init.js";
import { getDb } from "@/lib/db";
import {
  runQueuedSweep,
  runQueuedTrialSweep,
  type MonitorQueueMessage,
  type SweepEnv,
} from "@/lib/monitor/sweep-queue";
import type { TrialSweepEnv } from "@/lib/monitor/trial";

export default {
  fetch: handler.fetch,

  async queue(batch: MessageBatch, env: CloudflareEnv, ctx: ExecutionContext): Promise<void> {
    if (batch.queue !== "monitor-sweeps") {
      // Not ours — ack so an accidental binding doesn't retry-storm.
      for (const message of batch.messages) message.ack();
      return;
    }

    // The synthetic request only seeds process.env/origin on the isolate's
    // first invocation; APP_URL keeps the origin honest if that happens here.
    const contextRequest = new Request(env.APP_URL ?? "https://imagevault.ai/");

    await runWithCloudflareRequestContext(contextRequest, env, ctx, (async () => {
      const db = getDb();
      const baseUrl = process.env.NEXT_PUBLIC_BASE_URL ?? "https://imagevault.ai";
      for (const message of batch.messages) {
        const body = message.body as MonitorQueueMessage | undefined;
        if (body?.type === "likeness_sweep") {
          // Never throws: failures are recorded on the scan row, and a
          // redelivery after paid discovery must not re-run — so every
          // handled message is acked. Redelivery is reserved for consumers
          // that die outright.
          await runQueuedSweep(env as unknown as SweepEnv, db, body, message.attempts, baseUrl);
        } else if (body?.type === "trial_sweep") {
          // Same never-throws contract, recorded on the trial row.
          await runQueuedTrialSweep(env as unknown as TrialSweepEnv, db, body, message.attempts);
        }
        message.ack();
      }
      return new Response(null);
    }) as () => Promise<Response>);
  },
} satisfies ExportedHandler<CloudflareEnv>;

// Durable Objects used by the OpenNext runtime must be re-exported from the
// wrangler entrypoint module (unused under the default open-next.config.ts,
// but kept aligned with the generated worker's export surface).
// eslint-disable-next-line @typescript-eslint/ban-ts-comment -- resolves only after `npm run cf:build`, so ts-expect-error would flip post-build
// @ts-ignore
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";
